smash> smash> smash> smash> smash> test_redirect
smash> smash> again_redirect
smash> smash> again_redirect
test_redirect
smash> smash> smash pid is 1
smash> smash> smash pid is 1
smash pid is 1
smash> smash> smash pid is 1
smash> mypid
new
smash> smash> smash> [1] sleep 100& : 2 X secs
smash> smash> smash> smash> smash> k
mypid
new
s
t
smash> smash> k
mypid
new
p
s
t
smash> k
mypid
new
p
s
t
smash> smash> smash> before
smash> again_redirect
test_redirect
smash> smash> smash> smash> k
mypid
p
s
t
smash> smash> k
mypid
new
p
s
t
smash> k
mypid
new
p
s
t
smash> smash> smash> k
mypid
new
p
s
t
smash> k
mypid
new
p
s
t
smash> smash> smash> k
mypid
new
p
s
t
smash> smash> smash> k
mypid
new
p
s
t
test
smash> smash> 0
2
end: 4
smash> smash> smash> smash: sending SIGKILL signal to 1 jobs:
2: sleep 100&
